/*
MIT License

Copyright(c) 2023 Klara Košèeviæ

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KKošèeviæ.SolutionFileSorter.VSExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "SolutionFileSorter.174ef47e-feac-4a26-9e71-7566c9439c82";
        public const string Name = "SolutionFileSorter";
        public const string Description = @"SolutionFileSorter is a Visual Studio extension that provides the functionality to alphabetically sort projects within an open .sln (solution) file. This extension offers three methods of sorting projects: via a button within the Visual Studio solution, upon closing the solution, and through a console application for the given solution.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Klara Košèeviæ";
        public const string Tags = "";
    }
}
