// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KKoščević.SolutionFileSorter.VSExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "SolutionFileSorter.174ef47e-feac-4a26-9e71-7566c9439c82";
        public const string Name = "SolutionFileSorter";
        public const string Description = @"SolutionFileSorter provides the functionality to alphabetically sort projects within an open .sln file. Two methods of sorting projects: via a button and upon closing the solution.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Klara Koščević";
        public const string Tags = "";
    }
}
